### ISSUE TITLE
Base64EncodePublicKey/Base64EncodeSalt are missing 

### ISSUE THREAD

**Issue by minimatrix** [LogicSoftware/WebPushEncryption#1]
I tried to use this as shown in the Usage section. 

However both Base64Encode variables for the Salt/PublicKey aren't availale to me. I don't believe that I can just Base64 Encode the Salt/PublicKey values that are available in encryptedPayload.PublicKey as this needs to be a URLsafe Base64 encoding?

**Comment by norniel** [comment]
You mean - extensionMethods encryptedPayload.Base64EncodePublicKey() and encryptedPayload.Base64EncodeSalt() are not available?

**Comment by minimatrix** [comment]
Hi Norniel, yes that's correct, apologies for my terrible explanation

**Comment by PashaPash** [comment]
hi @minimatrix. Extension methods are declared in `LogicSoftware.WebPushEncryption`, so you should import namespace to make them available:

    using LogicSoftware.WebPushEncryption;

will update readme to fix that
